name: pi-ansible
services:
  control-node:
    build:
      context: ./control-node
    image: ansible-control-node
    volumes:
      - shared-volume:/shared-files
      - ./control-node/ansible:/ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False

  host:
    build:
      context: ./host
    image: ansible-host
    volumes:
      - shared-volume:/shared-files
    depends_on:
      - control-node
    scale: 1

volumes:
  shared-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs